---
# Run Mongodb Playbook
- name: Running MongoDB Playbook
  import_playbook: provision_mongodb.yml

# Run Nginx Playbook
- name: Running Nginx Playbook
  import_playbook: provision_nginx_proxy.yml

# Install nodejs and NPM
- hosts: web
  gather_facts: true
  become: true

  tasks:
  - name: Cloning CI/CD Jenkins repo
    shell: |
      cd /home/ubuntu/
      rm -rf eng84_cicd_jenkins
      git clone -b main https://github.com/William-King977/eng84_cicd_jenkins.git

  - name: Install nodejs
    shell: |
      curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
      apt-get install nodejs -y

  - name: Install NPM
    npm:
      path: /home/ubuntu/eng84_cicd_jenkins/app
      global: yes

  - name: Download latest npm + Mongoose
    shell: |
      cd /home/ubuntu/eng84_cicd_jenkins/app/
      npm install -g npm@latest
      npm install mongoose -y

  # Installing pm2
  - name: Install pm2
    npm:
      name: pm2
      global: yes

  - name: Seeding and running the (web) app
    shell: |
      cd /home/ubuntu/eng84_cicd_jenkins/app/
      node seeds/seed.js

      pm2 kill
      pm2 start app.js
    environment:
      DB_HOST: mongodb://db_private_ip:27017/posts?authSource=admin
    become_user: root
